//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ontap2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sanpham
    {
        public Sanpham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.MauSacs = new HashSet<MauSac>();
        }
    
        public int SanphamID { get; set; }
        [Required]
        [RegularExpression(@"^[\p{L}].*", ErrorMessage = "Tên sản phẩm phải bắt đầu bằng chữ cái")]
        [Display(Name = "Tên sản phẩm")]
        public string TenSanpham { get; set; }
        [Required]
        [RegularExpression(@"^[\p{L}].*", ErrorMessage = "Mô tả phải bắt đầu bằng chữ cái")]
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }
        [Required]
        [RegularExpression(@"^\d+$", ErrorMessage = "Giá chỉ được nhập số")]
        [Display(Name = "Giá")]
        public decimal Gia { get; set; }
        [Required]
        [Display(Name = "Trạng thái")]
        public Nullable<byte> TrangThai { get; set; }
        //[RegularExpression(@"^.+\.jpg$", ErrorMessage = "Ảnh phải có phần mở rộng là .jpg")]
        [Display(Name = "Ảnh đại diện")]
        public string AnhDaiDien { get; set; }
        [Required]
        [Display(Name = "Nổi bật")]
        public Nullable<byte> NoiBat { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [Display(Name = "Phân loại sản phẩm")]
        public Nullable<int> PhanLoaiSanPhamID { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual PhanLoaiSanPham PhanLoaiSanPham { get; set; }
        public virtual ICollection<MauSac> MauSacs { get; set; }
    }
}
